version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: go-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: goexpert
    ports:
      - "3306:3306"